name: Install Linien
description: Install all linien packages

runs:
  using: "composite"
  steps:
    - name: Install linien-common
      shell: bash
      working-directory: linien-common
      run: pip install .

    - name: Install linien-server
      shell: bash
      working-directory: linien-server
      run: pip install .

    - name: Install linien-client
      shell: bash
      working-directory: linien-client
      run: pip install .

    - name: Install linien-gui
      shell: bash
      working-directory: linien-gui
      run: pip install .
