name: Install Linien
description: Checkout the repository and install all linien packages

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install linien-common
      working-directory: linien-common
      run: pip install .

    - name: Install linien-server
      working-directory: linien-server
      run: pip install .

    - name: Install linien-client
      working-directory: linien-client
      run: pip install .

    - name: Install linien-gui
      working-directory: linien-gui
      run: pip install .
