name: Run Mypy

on:
  workflow_dispatch:
  push:
    paths:
      - linien-common/**
      - linien-client/**
      - linien-gui/**
      - linien-server/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install linien-common
        working-directory: linien-common
        run: pip install .

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-appdirs  

      - name: mypy for linien-common
        run: mypy linien-common

