name: Run Mypy

on:
  workflow_dispatch:
  push:
    paths:
      - linien-common/**
      - linien-client/**
      - linien-gui/**
      - linien-server/**

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Linien
        uses: /home/runner/work/linien/linien/.github/actions/install-linien

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-appdirs pyqt5-stubs

      - name: mypy for linien-common
        run: mypy linien-common/linien_common

      - name: mypy for linien-server
        run: mypy linien-server/linien_server

      - name: mypy for linien-client
        run: mypy linien-client/linien_client

      - name: mypy for linien-gui
        run: mypy linien-gui/linien_gui      