name: Upload Python Package to TestPyPI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build linien-common
        working-directory: linien-common
        run: python -m build

      - name: Build linien-server
        working-directory: linien-server
        run: python -m build

      - name: Build linien-client
        working-directory: linien-client
        run: python -m build

      - name: Build linien-gui
        working-directory: linien-gui
        run: python -m build

      - name: Publish linien-common to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          package_dir: linien-common/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish linien-server to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          package_dir: linien-server/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish linien-client to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          package_dir: linien-client/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish linien-gui to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          package_dir: linien-gui/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
