name: Pyinstaller Linux (new)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - run: sudo apt-get install -y qttools5-dev-tools binutils

      - run: pip install pyinstaller

      - name: Install linien-common
        working-directory: linien-common
        run: pip install .

      - name: Install linien-client
        working-directory: linien-client
        run: pip install .

      - name: Install linien-gui
        working-directory: linien-gui
        run: pip install .

      - run: pyinstaller pyinstaller.spec
        working-directory: linien-gui

      - uses: actions/upload-artifact@v3
        with:
          name: linien-gui-linux
          path: linien-gui/dist/*
