name: Pyinstaller Linux

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version_name:
        description: "Version name"
        required: true

env:
  INPUT_VERSION_NAME: ${{ github.event.inputs.version_name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: create VERSION file
        run: echo "$INPUT_VERSION_NAME" > linien/VERSION

      # NOTE: we hardcode the version of requirements here because the new pip
      #       resolver otherwise takes ages
      # ANOTHER NOTE: scipy is fixed to 1.4.1 because of problems with pyinstaller
      - name: create requirements file
        run: cp requirements_gui.txt requirements.txt

      - name: PyInstaller Linux
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: .

      - uses: actions/upload-artifact@v2
        with:
          name: my-exe
          path: dist/linux
