name: Run PyTest

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/pytest.yml
      - gateware/**
      - linien-common/**
      - linien-server/**
      - tests/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Linien
        uses: ./.github/actions/install-linien

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest migen pytest-plt git+https://github.com/m-labs/misoc

      - name: Test with pytest
        run: pytest .
