name: Run PyTest and Mypy

on:
  workflow_dispatch:
  push:
    paths:
      - gateware/**
      - linien-common/**
      - linien-server/**
      - tests/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install linien-common
        working-directory: linien-common
        run: pip install .

      - name: Install linien-server
        working-directory: linien-server
        run: pip install .

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest migen pytest-plt git+https://github.com/m-labs/misoc mypy types-appdirs  

      - name: Test with pytest
        run: pytest .

      - name: mypy for linien-common
        run: mypy linien-common

      - name: mypy for linien-server
        run: mypy linien-server

      - name: mypy for linien-client
        run: mypy linien-client

      - name: mypy for linien-gui
        run: mypy linien-gui
